### ISSUE TITLE
Scheduled alarms don't work.

### ISSUE THREAD

**Issue by fernferret** [fernferret/40Winks#1]
Title

**Comment by jetheis** [comment]
There doesn't seem to be much of anything in this repo. Did we fork into a proper organization and then lose it? What we've got here doesn't seem up to date at all.

**Comment by fernferret** [comment]
Doesn't look like it, did we just not push? Do you still have the repo? (I do not)

**Comment by jetheis** [comment]
I don't either. Looks like we might be redoing a lot of work.

**Comment by fernferret** [comment]
Could just start fresh, we both know a lot more now...

**Comment by fernferret** [comment]
FYI, I picked up a book on Android/X10 integration. I want my lights to turn on in the morning #featurecreep

**Comment by jetheis** [comment]
Haha very nice. Yeah I feel like the code we wrote before is probably pretty bad. I didn't even know what an AsyncTask was back then. It's probably for the best.
